# About the author {-}


**Jacob Kaplan** is the Chief Data Scientist of the Research on Policing Reform and Accountability (RoPRA), a multi-institution team of researchers studying policing. His current appointment is at the Princeton School of Public and International Affairs. He holds a PhD and a master's degree in criminology from the University of Pennsylvania and a bachelor's degree in criminal justice from California State University, Sacramento. His research focuses on Crime Prevention Through Environmental Design (CPTED), specifically on the effect of outdoor lighting on crime. He is the author of several R packages that make it easier to work with data, including  [fastDummies](https://jacobkap.github.io/fastDummies/) and [asciiSetupReader](https://jacobkap.github.io/asciiSetupReader/). His [website](http://jacobdkaplan.com/) allows easy analysis of crime-related data and he has released over a [dozen crime data sets](http://jacobdkaplan.com/data.html) (primarily FBI UCR data) on openICPSR that he has compiled, cleaned, and made available to the public. He is also the author of books on the two primary criminal justice datasets, the FBI's [Uniform Crime Reporting (UCR) Program Data](https://ucrbook.com/), and the FBI's [National Incident Based Reporting System (NIBRS)](https://nibrsbook.com/) data. 


For a list of papers he has written (including working papers), please see [here](http://jacobdkaplan.com/research.html).

For a list of data sets he has cleaned, aggregated, and made public, please see [here](http://jacobdkaplan.com/data.html).

For a list of R packages he has created, please see [here](https://jacobdkaplan.com/packages.html).
