# Collaboration - Dealing with people

In Chapter \@ref(collaboration) we discussed the technical aspects of collaborating with other people - documentation, unit tests, code review, etc. In this chapter we'll deal with the trickier aspect of collaboration: figuring out who to collaborate with and working with them. As with Chapter \@ref(on-saying-no), this chapter is geared towards academics who are conducting research, though the principles likely apply to other fields too. As this chapter focuses on collaborating in research projects, it may differ from data projects - though in my experience both kinds of projects are fairly similar.

## Choosing a team

The most important part of a project is who you work with. Your team essentially chooses how painful a project will be - a great team makes even highly complicated projects fun; a terrible team can make the easiest projects painful. Ideally you'll work with a group of peopple 

### Setting a team time

### Ask people you trust about possible collaborators

If you don't know much about someone that you may collaborate with, trying to find out as much as you can. A small part of this will be public, through data such as the person's bio on their website or their CV.^[If you don't have you own website as an academic, I highly recommend you make one. Websites now are very easy and quick to make on a site like Wix or WordPress (neither of which I am affiliated with in any way) and are now an essential tool for people on the job market.] You can get some info like where they generally publish, what kind of research they do, and who they work with. But it misses the most important part: if they're a good person to collaborate with. Since academia is a small world, there's a good chance that someone you know and trust - a collaborator, a friend, your advisor, etc. - knows of this person and can tell you about them. 

### Understanding people's goals

One misconception that some people have about academia is that everyone is there to do research to further their understanding of the world. This may be the most common goal - and the one often explicitly claimed - but people are also interested in furthering political outcomes, getting funding, or gaining attention for themselves. Each of these goals has different audiences and levels of methodological rigor - academic goals require high levels of rigor and the end result is a peer-reviewed paper, political goals tend to just have correlations and weak methodologies with a goal of supporting a preconcieved notion rather than answering a question etc. 

A key part of 

### Understanding people's priorities

### Considering your own reputation



## Authorship

### Author order and responsibilities

### Co-first author

## Timelines and meetings

